# Generated by Django 5.0 on 2025-12-27 21:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemsettings_and_more"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="age_days",
            field=models.IntegerField(blank=True, help_text="Age in days", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="age_months",
            field=models.IntegerField(blank=True, help_text="Age in months", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="age_years",
            field=models.IntegerField(blank=True, help_text="Age in years", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="cnic",
            field=models.CharField(
                blank=True,
                help_text="National ID in format #####-#######-#",
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CNIC must be in format #####-#######-#",
                        regex="^\\d{5}-\\d{7}-\\d$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateField(
                blank=True, help_text="Date of birth (legacy field)", null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="father_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="Full name (alternative to first_name/last_name)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="is_offline_entry",
            field=models.BooleanField(
                default=False, help_text="True if originally created while offline"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="mrn",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Medical Record Number (auto-generated)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="origin_terminal",
            field=models.ForeignKey(
                blank=True,
                help_text="Terminal that created this registration (if known)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="core.labterminal",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                help_text="Sex (M/F/O)",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this record was synced to central server",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone must be a valid Pakistani mobile number",
                        regex="^(\\+92|0)?3\\d{9}$",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["mrn"], name="patients_mrn_5d1fc1_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["patient_id"], name="patients_patient_e63b14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["cnic"], name="patients_cnic_7e2ed8_idx"),
        ),
    ]
