# Generated by Django 5.0 on 2026-02-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_collectioncenter_labdailycounter_registrationcounter"),
        ("patients", "0003_patient_father_husband_and_default_referred_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="registration_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="core.collectioncenter",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="registration_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="registration_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Official Registration Number (YYMM-CC-SSSS)",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["registration_number"], name="patients_registr_6e1306_idx"
            ),
        ),
    ]
