# Generated by Django 5.0 on 2026-02-07 10:32

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_patient_registration_center_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="registration_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Official Registration Number (YYMM-CC-SSSS)",
                max_length=20,
                null=True,
                unique=True,
                validators=[apps.core.validators.validate_registration_number],
            ),
        ),
    ]
