# Generated by Django 5.0 on 2026-02-08 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Whatsapp number if different from phone', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone must be a valid Pakistani mobile number', regex='^(\\+92|0)?3\\d{9}$')]),
        ),
    ]
