# Generated by Django 5.0 on 2026-02-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_branch_tenantmrnsequence_orderidsequence_and_more"),
        ("patients", "0006_patient_whatsapp_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Owning tenant (lab).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="mrn",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Medical Record Number (auto-generated, unique per tenant)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.UniqueConstraint(
                fields=("tenant", "mrn"), name="unique_patient_mrn_per_tenant"
            ),
        ),
    ]
