# Generated by Django 5.0 on 2026-02-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("samples", "0002_alter_samplecollection_collected_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="postponement_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Collection"),
                    ("COLLECTED", "Collected"),
                    ("RECEIVED", "Received in Lab"),
                    ("REJECTED", "Rejected"),
                    ("POSTPONED", "Postponed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
