# Generated by Django 5.0 on 2026-02-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_branch_tenantmrnsequence_orderidsequence_and_more"),
        ("orders", "0007_order_collection_branch_order_processing_branch_and_more"),
        ("samples", "0003_sample_postponement_reason_alter_sample_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="sample_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Tenant-wide unique sample identifier (order-scoped).",
                max_length=80,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="samples",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="collected_at_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="samples_collected",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="sample",
            name="current_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="samples_current",
                to="core.branch",
            ),
        ),
        migrations.AddConstraint(
            model_name="sample",
            constraint=models.UniqueConstraint(
                fields=("tenant", "sample_id"), name="unique_sample_per_tenant"
            ),
        ),
    ]
