# Generated by Django 5.0 on 2026-02-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_sample_sample_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleCollection',
        ),
    ]
