# Generated by Django 5.2.7 on 2025-11-15 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_is_offline_entry_patient_origin_terminal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="age_days",
            field=models.IntegerField(blank=True, help_text="Age in days", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="age_months",
            field=models.IntegerField(blank=True, help_text="Age in months", null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="age_years",
            field=models.IntegerField(blank=True, help_text="Age in years", null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="patient",
            name="cnic",
            field=models.CharField(
                blank=True,
                help_text="National ID in format #####-#######-#",
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="CNIC must be in format #####-#######-#",
                        regex="^\\d{5}-\\d{7}-\\d$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="father_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
