version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lims
      POSTGRES_USER: lims
      POSTGRES_PASSWORD: lims
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://lims:lims@db:5432/lims
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./frontend/pages:/app/pages
      - ./frontend/tsconfig.json:/app/tsconfig.json
    depends_on:
      - api
    ports:
      - "3000:3000"

volumes:
  db_data:
