# Generated by Django 5.2.7 on 2025-11-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(max_length=100)),
                ("sample_type", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "turnaround_time_hours",
                    models.IntegerField(help_text="Expected TAT in hours"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "test_catalog",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="test_catalo_code_fbb87f_idx"),
                    models.Index(
                        fields=["category"], name="test_catalo_categor_66bf84_idx"
                    ),
                ],
            },
        ),
    ]
