# Generated by Django 5.2.7 on 2025-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_parameter_test_parameterquicktext_referencerange_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencerange",
            name="critical_high",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="referencerange",
            name="critical_low",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="referencerange",
            name="normal_high",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="referencerange",
            name="normal_low",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
    ]
