# Generated by Django 5.2.7 on 2025-11-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short unique identifier (e.g., 'LAB1-PC', 'RECEP-1')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this terminal",
                        max_length=255,
                    ),
                ),
                (
                    "offline_range_start",
                    models.PositiveIntegerField(
                        help_text="Start of the offline MRN range (inclusive)"
                    ),
                ),
                (
                    "offline_range_end",
                    models.PositiveIntegerField(
                        help_text="End of the offline MRN range (inclusive)"
                    ),
                ),
                (
                    "offline_current",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current position in the offline range (0 = unused)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this terminal is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lab_terminals",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="lab_termina_code_073e2b_idx"),
                    models.Index(
                        fields=["is_active"], name="lab_termina_is_acti_297fe2_idx"
                    ),
                ],
            },
        ),
    ]
