# Generated by Django 5.0

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabTerminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short unique identifier (e.g., 'LAB1-PC', 'RECEP-1')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this terminal", max_length=255
                    ),
                ),
                (
                    "offline_range_start",
                    models.PositiveIntegerField(
                        help_text="Start of the offline MRN range (inclusive)"
                    ),
                ),
                (
                    "offline_range_end",
                    models.PositiveIntegerField(
                        help_text="End of the offline MRN range (inclusive)"
                    ),
                ),
                (
                    "offline_current",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current position in the offline range (0 = unused)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this terminal is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lab Terminal",
                "verbose_name_plural": "Lab Terminals",
                "db_table": "lab_terminals",
                "ordering": ["code"],
            },
        ),
        migrations.AddIndex(
            model_name="labterminal",
            index=models.Index(fields=["code"], name="lab_termin_code_idx"),
        ),
        migrations.AddIndex(
            model_name="labterminal",
            index=models.Index(fields=["is_active"], name="lab_termin_is_acti_idx"),
        ),
    ]

