# Generated by Django 5.0 on 2025-12-27 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lab_name", models.CharField(default="Laboratory", max_length=255)),
                ("lab_address", models.TextField(blank=True, null=True)),
                ("lab_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("lab_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "lab_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Laboratory logo for reports",
                        null=True,
                        upload_to="settings/logos/",
                    ),
                ),
                (
                    "report_header",
                    models.TextField(
                        blank=True,
                        help_text="Custom header text for reports",
                        null=True,
                    ),
                ),
                (
                    "report_footer",
                    models.TextField(
                        blank=True,
                        help_text="Custom footer text for reports",
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="PKR", max_length=10)),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax rate as percentage",
                        max_digits=5,
                    ),
                ),
                ("email_host", models.CharField(blank=True, max_length=255, null=True)),
                ("email_port", models.IntegerField(default=587)),
                ("email_use_tls", models.BooleanField(default=True)),
                ("email_use_ssl", models.BooleanField(default=False)),
                (
                    "email_host_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_host_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_from",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("backup_enabled", models.BooleanField(default=False)),
                (
                    "backup_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
        migrations.RenameIndex(
            model_name="labterminal",
            new_name="lab_termina_code_073e2b_idx",
            old_name="lab_termin_code_idx",
        ),
        migrations.RenameIndex(
            model_name="labterminal",
            new_name="lab_termina_is_acti_297fe2_idx",
            old_name="lab_termin_is_acti_idx",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settings_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
