# Generated by Codex on 2026-01-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_add_lab_display_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labterminal",
            options={
                "verbose_name": "Lab Terminal",
                "verbose_name_plural": "Lab Terminals",
            },
        ),
        migrations.AlterModelTable(
            name="labterminal",
            table="core_labterminal",
        ),
        migrations.RemoveIndex(
            model_name="labterminal",
            name="lab_termina_code_073e2b_idx",
        ),
        migrations.RemoveIndex(
            model_name="labterminal",
            name="lab_termina_is_acti_297fe2_idx",
        ),
        migrations.RemoveField(
            model_name="labterminal",
            name="code",
        ),
        migrations.RemoveField(
            model_name="labterminal",
            name="offline_current",
        ),
        migrations.RemoveField(
            model_name="labterminal",
            name="offline_range_end",
        ),
        migrations.RemoveField(
            model_name="labterminal",
            name="offline_range_start",
        ),
        migrations.RemoveField(
            model_name="labterminal",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="labterminal",
            name="location",
            field=models.CharField(blank=True, help_text="Physical location of terminal", max_length=255),
        ),
        migrations.AlterField(
            model_name="labterminal",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="labterminal",
            name="name",
            field=models.CharField(help_text="Terminal name or identifier", max_length=255),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="lab_logo",
            field=models.ImageField(
                blank=True,
                help_text="Laboratory logo for reports and UI",
                null=True,
                upload_to="settings/logos/",
            ),
        ),
        migrations.CreateModel(
            name="PrintTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_key", models.CharField(max_length=100, unique=True)),
                ("type", models.CharField(choices=[("REPORT", "Report"), ("RECEIPT", "Receipt")], max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "config",
                    models.JSONField(
                        default={
                            "paper_size": "A4",
                            "margins": {"top": 1.0, "right": 1.0, "bottom": 1.0, "left": 1.0},
                            "font_scale": 1.0,
                            "show_logo": True,
                            "show_header_image": True,
                            "show_footer_image": True,
                            "show_disclaimer": True,
                            "show_signatures": True,
                            "show_qr": False,
                            "show_barcode": False,
                        }
                    ),
                ),
                ("disclaimer_text", models.TextField(blank=True)),
                ("signatories", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Print Template",
                "verbose_name_plural": "Print Templates",
                "db_table": "print_templates",
                "ordering": ["type", "name"],
            },
        ),
    ]
