# Generated by Django 5.0 on 2026-01-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_lab_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labterminal',
            options={'verbose_name': 'Lab Terminal', 'verbose_name_plural': 'Lab Terminals'},
        ),
        migrations.RemoveIndex(
            model_name='labterminal',
            name='lab_termina_code_073e2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='labterminal',
            name='lab_termina_is_acti_297fe2_idx',
        ),
        migrations.RemoveField(
            model_name='labterminal',
            name='code',
        ),
        migrations.RemoveField(
            model_name='labterminal',
            name='offline_current',
        ),
        migrations.RemoveField(
            model_name='labterminal',
            name='offline_range_end',
        ),
        migrations.RemoveField(
            model_name='labterminal',
            name='offline_range_start',
        ),
        migrations.RemoveField(
            model_name='labterminal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='labterminal',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location of terminal', max_length=255),
        ),
        migrations.AlterField(
            model_name='labterminal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='labterminal',
            name='name',
            field=models.CharField(help_text='Terminal name or identifier', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='lab_logo',
            field=models.ImageField(blank=True, help_text='Laboratory logo for reports and UI', null=True, upload_to='settings/logos/'),
        ),
        migrations.AlterModelTable(
            name='labterminal',
            table='core_labterminal',
        ),
    ]
