# Generated by Codex on 2026-01-31

from django.db import migrations


def seed_print_templates(apps, schema_editor):
    PrintTemplate = apps.get_model("core", "PrintTemplate")
    if PrintTemplate.objects.exists():
        return

    PrintTemplate.objects.create(
        template_key="report_default",
        type="REPORT",
        name="Default Report",
        description="Default report template",
        is_active=True,
        disclaimer_text="This report is electronically generated and valid without signature unless otherwise noted.",
        signatories=[
            {"name": "Lab Technician", "title": "Technician"},
            {"name": "Pathologist", "title": "Pathologist"},
        ],
    )

    PrintTemplate.objects.create(
        template_key="receipt_default",
        type="RECEIPT",
        name="Default Receipt",
        description="Default receipt template",
        is_active=True,
        disclaimer_text="Payments are non-refundable once processed.",
        signatories=[],
    )


def unseed_print_templates(apps, schema_editor):
    PrintTemplate = apps.get_model("core", "PrintTemplate")
    PrintTemplate.objects.filter(template_key__in=["report_default", "receipt_default"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_printtemplate_and_labterminal_cleanup"),
    ]

    operations = [
        migrations.RunPython(seed_print_templates, unseed_print_templates),
    ]
