# Generated by Django 5.0 on 2026-02-06 20:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_printtemplate_alter_labterminal_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="2-digit unique code (e.g., '00' for Head Office)",
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Code must be 2 digits (00-99)"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Collection Center",
                "verbose_name_plural": "Collection Centers",
                "db_table": "core_collection_centers",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LabDailyCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="Date of processing")),
                ("last_value", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.collectioncenter",
                    ),
                ),
            ],
            options={
                "db_table": "core_lab_daily_counters",
                "indexes": [
                    models.Index(
                        fields=["date", "center"], name="core_lab_da_date_184e7d_idx"
                    )
                ],
                "unique_together": {("date", "center")},
            },
        ),
        migrations.CreateModel(
            name="RegistrationCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yymm",
                    models.CharField(
                        help_text="Year-Month string (e.g., '2602')", max_length=4
                    ),
                ),
                ("last_value", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.collectioncenter",
                    ),
                ),
            ],
            options={
                "db_table": "core_registration_counters",
                "indexes": [
                    models.Index(
                        fields=["yymm", "center"], name="core_regist_yymm_3f2031_idx"
                    )
                ],
                "unique_together": {("yymm", "center")},
            },
        ),
    ]
