# Generated by Django 5.0 on 2026-02-10 22:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_collectioncenter_labdailycounter_registrationcounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short stable tenant code used in IDs (e.g., LAB).",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "core_tenants",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Numeric branch code (00-99).",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Code must be 2 digits (00-99)"
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "capability_mode",
                    models.CharField(
                        choices=[
                            ("COLLECT_ONLY", "Collection Only"),
                            ("COLLECT_AND_PROCESS", "Collect & Process"),
                            ("HQ_PROCESSING", "HQ / Processing"),
                        ],
                        default="COLLECT_ONLY",
                        max_length=32,
                    ),
                ),
                (
                    "is_hq",
                    models.BooleanField(
                        default=False,
                        help_text="True when branch is HQ; enforced for code 00",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="branches",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "core_branches",
                "ordering": ["tenant_id", "code"],
            },
        ),
        migrations.CreateModel(
            name="TenantMrnSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_suffix", models.CharField(help_text="YY format", max_length=2)),
                ("last_seq", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mrn_sequences",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_tenant_mrn_sequences",
            },
        ),
        migrations.CreateModel(
            name="OrderIdSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("last_seq", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_sequences",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_sequences",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "core_order_id_sequences",
                "indexes": [
                    models.Index(
                        fields=["tenant", "branch", "date"],
                        name="core_order__tenant__f44f65_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="orderidsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "branch", "date"),
                name="unique_order_seq_per_branch_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="unique_branch_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmrnsequence",
            index=models.Index(
                fields=["tenant", "year_suffix"], name="core_tenant_tenant__ab5f6c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantmrnsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "year_suffix"), name="unique_tenant_year_mrn_seq"
            ),
        ),
    ]
