# Generated by Django 5.0 on 2026-02-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenantsettings_enable_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantsettings',
            name='sample_workflow_enabled',
            field=models.BooleanField(default=False, help_text='When True, sample collection/receiving is required before result entry. When False, orders go directly to result entry after receipt/payment.'),
        ),
    ]
