# Generated by Django 5.0 on 2025-11-26 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Test Category",
                "verbose_name_plural": "Test Categories",
                "db_table": "test_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("loinc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("sample_type", models.CharField(max_length=100)),
                (
                    "sample_volume",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "turnaround_time",
                    models.IntegerField(help_text="Turnaround time in hours"),
                ),
                ("instructions", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tests",
                        to="laboratory.testcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test",
                "verbose_name_plural": "Tests",
                "db_table": "tests",
                "ordering": ["test_code"],
            },
        ),
        migrations.CreateModel(
            name="TestPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "panel_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("panel_name", models.CharField(max_length=200)),
                ("sample_type", models.CharField(max_length=100)),
                (
                    "sample_volume",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "turnaround_time",
                    models.IntegerField(help_text="Turnaround time in hours"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="panels",
                        to="laboratory.testcategory",
                    ),
                ),
                (
                    "tests",
                    models.ManyToManyField(related_name="panels", to="laboratory.test"),
                ),
            ],
            options={
                "verbose_name": "Test Panel",
                "verbose_name_plural": "Test Panels",
                "db_table": "test_panels",
                "ordering": ["panel_code"],
            },
        ),
        migrations.CreateModel(
            name="TestParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parameter_name", models.CharField(max_length=200)),
                ("loinc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("unit", models.CharField(max_length=50)),
                (
                    "reference_min_male",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_max_male",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_min_female",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_max_female",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("decimal_places", models.IntegerField(default=2)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="laboratory.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Parameter",
                "verbose_name_plural": "Test Parameters",
                "db_table": "test_parameters",
                "ordering": ["test", "display_order", "parameter_name"],
            },
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(fields=["test_code"], name="tests_test_co_b40f6a_idx"),
        ),
        migrations.AddIndex(
            model_name="test",
            index=models.Index(
                fields=["category", "is_active"], name="tests_categor_853c05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testpanel",
            index=models.Index(
                fields=["panel_code"], name="test_panels_panel_c_c4b411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testpanel",
            index=models.Index(
                fields=["category", "is_active"], name="test_panels_categor_158b34_idx"
            ),
        ),
    ]
