# Generated by Django 6.0 on 2025-12-31 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("data_type", models.CharField(default="Numeric", max_length=50)),
                ("editor_type", models.CharField(default="Plain", max_length=50)),
                (
                    "decimal_places",
                    models.IntegerField(blank=True, default=2, null=True),
                ),
                ("allowed_values", models.TextField(blank=True)),
                ("is_calculated", models.BooleanField(default=False)),
                ("calculation_formula", models.TextField(blank=True)),
                ("flag_direction", models.CharField(default="Both", max_length=20)),
                ("has_quick_text", models.BooleanField(default=False)),
                ("external_code_type", models.CharField(blank=True, max_length=50)),
                ("external_code_value", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parameter",
                "verbose_name_plural": "Parameters",
                "db_table": "parameters",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="parameters_code_38502b_idx"),
                    models.Index(
                        fields=["active"], name="parameters_active_6dece1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParameterQuickText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_title", models.CharField(max_length=255)),
                ("template_body", models.TextField()),
                ("language", models.CharField(default="EN", max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_texts",
                        to="laboratory.parameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parameter Quick Text",
                "verbose_name_plural": "Parameter Quick Texts",
                "db_table": "parameter_quick_texts",
                "ordering": ["parameter", "template_title"],
                "indexes": [
                    models.Index(
                        fields=["parameter"], name="parameter_q_paramet_210126_idx"
                    )
                ],
                "unique_together": {("parameter", "template_title", "language")},
            },
        ),
        migrations.CreateModel(
            name="ParameterReferenceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_code", models.CharField(blank=True, max_length=50)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("All", "All")],
                        default="All",
                        max_length=20,
                    ),
                ),
                ("age_min", models.IntegerField(default=0)),
                ("age_max", models.IntegerField(default=999)),
                (
                    "age_unit",
                    models.CharField(
                        choices=[
                            ("Years", "Years"),
                            ("Months", "Months"),
                            ("Days", "Days"),
                        ],
                        default="Years",
                        max_length=20,
                    ),
                ),
                ("population_group", models.CharField(default="Adult", max_length=50)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "normal_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "normal_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("reference_text", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="laboratory.parameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Range",
                "verbose_name_plural": "Reference Ranges",
                "db_table": "parameter_reference_ranges",
                "ordering": ["parameter", "age_min"],
                "indexes": [
                    models.Index(
                        fields=["parameter", "sex", "age_min"],
                        name="parameter_r_paramet_376bc9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReferenceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Minimum age in years (null = no minimum)",
                        null=True,
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum age in years (null = no maximum)",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Both", "Both"),
                        ],
                        default="Both",
                        max_length=10,
                    ),
                ),
                (
                    "reference_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "reference_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reference_ranges_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="laboratory.testparameter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reference Range",
                "verbose_name_plural": "Reference Ranges",
                "db_table": "reference_ranges",
                "ordering": ["parameter", "age_min", "gender", "-version"],
                "indexes": [
                    models.Index(
                        fields=["parameter", "is_active"],
                        name="reference_r_paramet_224919_idx",
                    ),
                    models.Index(
                        fields=["parameter", "gender", "age_min", "age_max"],
                        name="reference_r_paramet_7f6d7e_idx",
                    ),
                ],
                "unique_together": {
                    ("parameter", "age_min", "age_max", "gender", "version")
                },
            },
        ),
        migrations.CreateModel(
            name="TestParameterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("section_header", models.CharField(blank=True, max_length=255)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("show_on_report", models.BooleanField(default=True)),
                (
                    "default_reference_profile_id",
                    models.CharField(blank=True, max_length=50),
                ),
                ("delta_check_enabled", models.BooleanField(default=False)),
                (
                    "panic_low_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "panic_high_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("comment_template_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_links",
                        to="laboratory.parameter",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_links",
                        to="laboratory.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Parameter Link",
                "verbose_name_plural": "Test Parameter Links",
                "db_table": "test_parameter_links",
                "ordering": ["test", "display_order"],
                "indexes": [
                    models.Index(
                        fields=["test", "display_order"],
                        name="test_parame_test_id_efc2a8_idx",
                    )
                ],
                "unique_together": {("test", "parameter")},
            },
        ),
    ]
