# Generated by Django 5.0 on 2026-01-22 01:06

import apps.laboratory.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_add_parameter_id_validation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testparameter',
            options={'ordering': ['test', 'display_order'], 'verbose_name': 'Test Parameter Mapping', 'verbose_name_plural': 'Test Parameter Mappings'},
        ),
        # Removed RemoveIndex because 0003 already handled index cleanup
        # migrations.RemoveIndex(
        #    model_name='parameter',
        #    name='parameters_code_38502b_idx',
        # ),
        migrations.RenameField(
            model_name='parameter',
            old_name='name',
            new_name='parameter_name',
        ),
        # Fix Test Model PK
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AddField(
            model_name='test',
            name='legacy_test_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='test_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        # Link TestParameter to Parameter
        migrations.AddField(
            model_name='testparameter',
            name='parameter',
            field=models.ForeignKey(default='p1', on_delete=django.db.models.deletion.CASCADE, related_name='test_mappings', to='laboratory.parameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testparameter',
            name='reportable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='parameter_id',
            field=models.CharField(help_text='Parameter ID in format p<number> (e.g., p1, p2, p53)', max_length=100, primary_key=True, serialize=False, validators=[apps.laboratory.models.validate_parameter_id]),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parameterreferencerange',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_reference_ranges', to='laboratory.parameter'),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='parameter_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_parameters', to='laboratory.test'),
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['parameter_id'], name='parameters_paramet_612311_idx'),
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='critical_high',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='critical_low',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='decimal_places',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='loinc_code',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='reference_max_female',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='reference_max_male',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='reference_min_female',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='reference_min_male',
        ),
        migrations.RemoveField(
            model_name='testparameter',
            name='unit',
        ),
        migrations.AlterUniqueTogether(
            name='testparameter',
            unique_together={('test', 'parameter')},
        ),
    ]
