# Generated by Django 5.0 on 2026-01-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_testparameter_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='parameter',
            name='parameters_param_id_idx',
        ),
        migrations.RenameIndex(
            model_name='parameter',
            new_name='parameters_active_6dece1_idx',
            old_name='parameters_active_idx',
        ),
    ]
