# Generated by Codex on 2026-01-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0004_alter_testparameter_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("strict", models.BooleanField(default=True)),
                ("allow_defaults", models.BooleanField(default=False)),
                ("mode", models.CharField(default="upsert", max_length=20)),
                ("dry_run", models.BooleanField(default=True)),
                ("summary_json", models.JSONField(default=dict)),
                ("errors_json", models.JSONField(default=list)),
                ("warnings_json", models.JSONField(default=list)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Import Job",
                "verbose_name_plural": "Catalog Import Jobs",
                "db_table": "catalog_import_jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
