# Generated by Django 5.0 on 2026-01-22 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_remove_parameter_parameters_param_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['parameter_id'], 'verbose_name': 'Parameter', 'verbose_name_plural': 'Parameters'},
        ),
    ]
