# Generated by Django 5.0 on 2026-02-06 00:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "laboratory",
            "0005_catalogimportjob_alter_parameterquicktext_options_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="SELECT 1;",  # No-op that works everywhere
                    reverse_sql="SELECT 1;",
                )
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="parameter",
                    new_name="parameters_active_6dece1_idx",
                    old_name="parameters_active_idx",
                )
            ],
        ),
    ]
