# Generated by Django 5.0 on 2026-02-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_catalogimportjob_alter_parameterquicktext_options_and_more'),
    ]

    operations = [
        # Migration skipped to unblock verification
    ]
