# Generated by Django 5.0 on 2026-02-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_rename_parameters_active_idx_parameters_active_6dece1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameter',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If true, result value is mandatory for verification.'),
        ),
    ]
