# Generated by Django 5.0 on 2026-02-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0007_testparameter_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='footer_comments_static',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='force_separate_page',
            field=models.BooleanField(default=False, help_text='Force this test to start on a new page in reports'),
        ),
        migrations.AddField(
            model_name='test',
            name='omit_blank_parameters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='print_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='print_if_any_result_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='print_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='footer_comments_static',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='force_separate_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='omit_blank_parameters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='print_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='print_if_any_result_present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testpanel',
            name='print_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='allow_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='default_mode',
            field=models.CharField(choices=[('ALWAYS', 'Always'), ('IF_EMPTY', 'If Empty'), ('PER_VISIT', 'Per Visit')], default='IF_EMPTY', max_length=20),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='formula_dependencies',
            field=models.JSONField(blank=True, help_text='List of parameter IDs this depends on', null=True),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='formula_expression',
            field=models.TextField(blank=True, help_text='e.g. {WBC} * 10 or complex logic', null=True),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='is_printable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='is_required_for_verification',
            field=models.BooleanField(default=True, help_text='If true, result value is mandatory for verification.'),
        ),
        migrations.AddField(
            model_name='testparameter',
            name='value_source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('FORMULA', 'Formula'), ('INSTRUMENT', 'Instrument')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Legacy flag; use is_required_for_verification'),
        ),
    ]
