# Generated by Django 5.2.7 on 2025-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("RECEPTION", "Reception"),
                            ("PHLEBOTOMY", "Phlebotomy"),
                            ("TECHNOLOGIST", "Technologist"),
                            ("PATHOLOGIST", "Pathologist"),
                        ],
                        help_text="User role",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "can_register",
                    models.BooleanField(
                        default=False, help_text="Can register new patients"
                    ),
                ),
                (
                    "can_collect",
                    models.BooleanField(default=False, help_text="Can collect samples"),
                ),
                (
                    "can_enter_result",
                    models.BooleanField(
                        default=False, help_text="Can enter test results"
                    ),
                ),
                (
                    "can_verify",
                    models.BooleanField(
                        default=False, help_text="Can verify test results"
                    ),
                ),
                (
                    "can_publish",
                    models.BooleanField(
                        default=False, help_text="Can publish test results"
                    ),
                ),
                (
                    "can_edit_catalog",
                    models.BooleanField(
                        default=False, help_text="Can edit test catalog"
                    ),
                ),
                (
                    "can_edit_settings",
                    models.BooleanField(
                        default=False, help_text="Can edit system settings"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "role_permissions",
                "ordering": ["role"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_sample_collection",
                    models.BooleanField(
                        default=True, help_text="Enable manual sample collection step"
                    ),
                ),
                (
                    "enable_sample_receive",
                    models.BooleanField(
                        default=True,
                        help_text="Enable manual sample receive step in lab",
                    ),
                ),
                (
                    "enable_verification",
                    models.BooleanField(
                        default=True,
                        help_text="Require verification before publishing results",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workflow Settings",
                "verbose_name_plural": "Workflow Settings",
                "db_table": "workflow_settings",
            },
        ),
    ]
