# Generated by Django 5.2.7 on 2025-11-15 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("data_type", models.CharField(default="Numeric", max_length=50)),
                ("editor_type", models.CharField(default="Plain", max_length=50)),
                (
                    "decimal_places",
                    models.IntegerField(blank=True, default=2, null=True),
                ),
                ("allowed_values", models.TextField(blank=True)),
                ("is_calculated", models.BooleanField(default=False)),
                ("calculation_formula", models.TextField(blank=True)),
                ("flag_direction", models.CharField(default="Both", max_length=20)),
                ("has_quick_text", models.BooleanField(default=False)),
                ("external_code_type", models.CharField(blank=True, max_length=50)),
                ("external_code_value", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "parameters",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="parameters_code_38502b_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("test_type", models.CharField(default="Single", max_length=50)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("specimen_type", models.CharField(blank=True, max_length=100)),
                ("container_type", models.CharField(blank=True, max_length=100)),
                ("result_scale", models.CharField(blank=True, max_length=50)),
                ("default_method", models.CharField(blank=True, max_length=100)),
                ("default_tat_minutes", models.IntegerField(default=0)),
                ("default_print_group", models.CharField(blank=True, max_length=100)),
                (
                    "default_report_template",
                    models.CharField(blank=True, max_length=100),
                ),
                ("default_printer_code", models.CharField(blank=True, max_length=50)),
                ("billing_code", models.CharField(blank=True, max_length=50)),
                (
                    "default_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("external_code_type", models.CharField(blank=True, max_length=50)),
                ("external_code_value", models.CharField(blank=True, max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tests",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="tests_code_708059_idx"),
                    models.Index(
                        fields=["department"], name="tests_departm_9c86d2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ParameterQuickText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_title", models.CharField(max_length=255)),
                ("template_body", models.TextField()),
                ("language", models.CharField(default="EN", max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_texts",
                        to="catalog.parameter",
                    ),
                ),
            ],
            options={
                "db_table": "parameter_quick_texts",
                "ordering": ["parameter", "template_title"],
                "indexes": [
                    models.Index(
                        fields=["parameter"], name="parameter_q_paramet_210126_idx"
                    )
                ],
                "unique_together": {("parameter", "template_title", "language")},
            },
        ),
        migrations.CreateModel(
            name="ReferenceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_code", models.CharField(blank=True, max_length=50)),
                ("sex", models.CharField(default="All", max_length=20)),
                ("age_min", models.IntegerField(default=0)),
                ("age_max", models.IntegerField(default=999)),
                ("age_unit", models.CharField(default="Years", max_length=20)),
                ("population_group", models.CharField(default="Adult", max_length=50)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "normal_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "normal_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("reference_text", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_ranges",
                        to="catalog.parameter",
                    ),
                ),
            ],
            options={
                "db_table": "reference_ranges",
                "ordering": ["parameter", "age_min"],
                "indexes": [
                    models.Index(
                        fields=["parameter", "sex", "age_min"],
                        name="reference_r_paramet_c4fe1a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TestParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("section_header", models.CharField(blank=True, max_length=255)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("show_on_report", models.BooleanField(default=True)),
                (
                    "default_reference_profile_id",
                    models.CharField(blank=True, max_length=50),
                ),
                ("delta_check_enabled", models.BooleanField(default=False)),
                (
                    "panic_low_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "panic_high_override",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("comment_template_id", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_parameters",
                        to="catalog.parameter",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_parameters",
                        to="catalog.test",
                    ),
                ),
            ],
            options={
                "db_table": "test_parameters",
                "ordering": ["test", "display_order"],
                "indexes": [
                    models.Index(
                        fields=["test", "display_order"],
                        name="test_parame_test_id_cc38b0_idx",
                    )
                ],
                "unique_together": {("test", "parameter")},
            },
        ),
    ]
