# Generated by Django 5.0 on 2025-12-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="priority",
            field=models.CharField(
                choices=[
                    ("ROUTINE", "Routine"),
                    ("URGENT", "Urgent"),
                    ("STAT", "STAT"),
                ],
                default="ROUTINE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("COLLECTED", "Collected"),
                    ("IN_PROCESS", "In Process"),
                    ("VERIFIED", "Verified"),
                    ("PUBLISHED", "Published"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("COLLECTED", "Collected"),
                    ("IN_PROCESS", "In Process"),
                    ("VERIFIED", "Verified"),
                    ("PUBLISHED", "Published"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
    ]
