# Generated by Django 5.0 on 2026-02-06 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_collectioncenter_labdailycounter_registrationcounter"),
        ("orders", "0004_order_discount_percent_order_due_amount_and_more"),
        ("patients", "0004_patient_registration_center_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collection_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.collectioncenter",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="daily_serial",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="lab_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="lab_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Tube Label (MDD-XXX)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["lab_number"], name="orders_orde_lab_num_955db2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["lab_date", "collection_center", "daily_serial"],
                name="orders_orde_lab_dat_023ef0_idx",
            ),
        ),
    ]
