# Generated by Django 5.0 on 2026-02-07 10:32

from django.db import migrations, models

import apps.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_order_collection_center_order_daily_serial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="lab_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Tube Label (MDD-XXX)",
                max_length=20,
                null=True,
                validators=[apps.core.validators.validate_lab_number],
            ),
        ),
    ]
