# Generated by Django 5.0 on 2026-02-10 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_tenant_branch_tenantmrnsequence_orderidsequence_and_more"),
        ("orders", "0006_alter_order_lab_number"),
        ("patients", "0007_patient_tenant_alter_patient_mrn_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="collection_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_collected",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="processing_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_processing",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(db_index=True, editable=False, max_length=30),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("tenant", "order_id"), name="unique_order_id_per_tenant"
            ),
        ),
    ]
