# Generated by Django 5.0 on 2026-02-11 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_branch_tenantmrnsequence_orderidsequence_and_more'),
        ('orders', '0007_order_collection_branch_order_processing_branch_and_more'),
        ('patients', '0007_patient_tenant_alter_patient_mrn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['referred_by'], name='orders_orde_referre_ea752f_idx'),
        ),
    ]
