# Generated by Django 5.0.0 on 2026-02-11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def generate_backup_id():
    return str(uuid.uuid4())


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupArtifact",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=generate_backup_id,
                        editable=False,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("AUTO", "Automatic"), ("MANUAL", "Manual"), ("IMPORTED", "Imported")],
                        default="MANUAL",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("RUNNING", "Running"), ("SUCCESS", "Success"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("filename", models.CharField(blank=True, default="", max_length=1024)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "offsite_provider",
                    models.CharField(
                        choices=[("NONE", "None"), ("S3", "S3"), ("GDRIVE", "Google Drive")],
                        default="NONE",
                        max_length=16,
                    ),
                ),
                (
                    "offsite_status",
                    models.CharField(
                        choices=[
                            ("NOT_CONFIGURED", "Not configured"),
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_CONFIGURED",
                        max_length=20,
                    ),
                ),
                ("logs", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backups_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_create_backup", "Can create backup artifacts"),
                    ("can_restore_backup", "Can restore backup artifacts"),
                    ("can_download_backup", "Can download backup artifacts"),
                    ("can_delete_backup", "Can delete backup artifacts"),
                ],
            },
        ),
    ]
