# Generated by Django 5.0.0 on 2026-02-12

import apps.backups.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backups", "0002_assign_backup_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backupartifact",
            name="id",
            field=models.CharField(
                default=apps.backups.models.generate_backup_id,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
