import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { reportApi } from '../../api/services';
import type { Report } from '../../types';
import styles from './ReportsPage.module.css';

export default function ReportsPage() {
  const queryClient = useQueryClient();
  const [selectedOrderId, setSelectedOrderId] = useState<number | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  const { data: reportsData, isLoading, error } = useQuery({
    queryKey: ['reports', searchQuery],
    queryFn: () => reportApi.list({ ...(searchQuery && { search: searchQuery }) }),
  });

  const generateMutation = useMutation({
    mutationFn: (orderId: number) => reportApi.generate(orderId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['reports'] });
      alert('Report generated successfully!');
    },
  });

  const downloadMutation = useMutation({
    mutationFn: async (reportId: number) => {
      const blob = await reportApi.download(reportId);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `report_${reportId}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    },
  });

  const reports = reportsData?.results || [];

  const handleGenerate = () => {
    if (selectedOrderId) {
      generateMutation.mutate(selectedOrderId);
    }
  };

  const handleDownload = (reportId: number) => {
    downloadMutation.mutate(reportId);
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h1>Reports</h1>
        <div className={styles.headerActions}>
          <input
            type="number"
            placeholder="Order ID"
            value={selectedOrderId || ''}
            onChange={(e) => setSelectedOrderId(e.target.value ? Number(e.target.value) : null)}
            className={styles.orderInput}
          />
          <button
            onClick={handleGenerate}
            className={styles.generateButton}
            disabled={!selectedOrderId || generateMutation.isPending}
          >
            {generateMutation.isPending ? 'Generating...' : 'Generate Report'}
          </button>
        </div>
      </div>

      <div className={styles.filters}>
        <input
          type="text"
          placeholder="Search reports..."
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className={styles.searchInput}
        />
      </div>

      {isLoading ? (
        <div className={styles.loading}>Loading reports...</div>
      ) : error ? (
        <div className={styles.error}>Failed to load reports</div>
      ) : (
        <table className={styles.table}>
          <thead>
            <tr>
              <th>Order ID</th>
              <th>Generated At</th>
              <th>Generated By</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report) => (
              <tr key={report.id}>
                <td>{report.order_id_display || `Order #${report.order}`}</td>
                <td>{new Date(report.generated_at).toLocaleString()}</td>
                <td>{report.generated_by_name || '-'}</td>
                <td>
                  <span className={report.is_final ? styles.statusFinal : styles.statusDraft}>
                    {report.is_final ? 'Final' : 'Draft'}
                  </span>
                </td>
                <td>
                  <div className={styles.actions}>
                    <button
                      onClick={() => handleDownload(report.id)}
                      className={styles.downloadButton}
                      disabled={downloadMutation.isPending}
                    >
                      Download
                    </button>
                  </div>
                </td>
              </tr>
            ))}
            {reports.length === 0 && (
              <tr>
                <td colSpan={5} className={styles.noData}>
                  No reports found
                </td>
              </tr>
            )}
          </tbody>
        </table>
      )}
    </div>
  );
}
