import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { reportApi } from '../../api/services';
import type { Report } from '../../types';
import styles from './ReportsPage.module.css';

export default function ReportsPage() {
    const [retryCount, setRetryCount] = useState(0);

    const {
        data: reportsData,
        isLoading,
        isError,
        error,
        refetch
    } = useQuery({
        queryKey: ['reports', retryCount],
        queryFn: () => reportApi.list(),
        retry: 2,
        retryDelay: 1000,
    });

    const handleRetry = () => {
        setRetryCount(prev => prev + 1);
        refetch();
    };

    // Loading state
    if (isLoading) {
        return (
            <div className={styles.container}>
                <div className={styles.loadingContainer}>
                    <div className={styles.spinner}></div>
                    <p>Loading reports...</p>
                    <p className={styles.loadingHint}>This may take a few moments</p>
                </div>
            </div>
        );
    }

    // Error state with retry
    if (isError) {
        const errorMessage = (error as Error)?.message || 'Failed to load reports';
        return (
            <div className={styles.container}>
                <div className={styles.errorContainer}>
                    <div className={styles.errorIcon}>❌</div>
                    <h2>Failed to Load Reports</h2>
                    <p className={styles.errorMessage}>{errorMessage}</p>
                    <div className={styles.errorActions}>
                        <button className={styles.retryButton} onClick={handleRetry}>
                            Retry
                        </button>
                    </div>
                    {retryCount > 0 && (
                        <p className={styles.retryInfo}>Retry attempt: {retryCount}</p>
                    )}
                </div>
            </div>
        );
    }

    const reports = reportsData?.results || [];

    return (
        <div className={styles.container}>
            <div className={styles.header}>
                <h1>Reports</h1>
                <p className={styles.subtitle}>Generated laboratory reports</p>
            </div>

            {reports.length === 0 ? (
                <div className={styles.emptyState}>
                    <p>📄 No reports generated yet</p>
                </div>
            ) : (
                <div className={styles.reportsList}>
                    {reports.map((report: Report) => (
                        <div key={report.id} className={styles.reportCard}>
                            <div className={styles.reportHeader}>
                                <div className={styles.reportInfo}>
                                    <h3>Report #{report.id}</h3>
                                    <span className={styles.orderId}>Order: {report.order_id_display || report.order}</span>
                                </div>
                                <span className={`${styles.statusBadge} ${report.is_final ? styles.final : styles.draft}`}>
                                    {report.is_final ? 'Final' : 'Draft'}
                                </span>
                            </div>

                            <div className={styles.reportDetails}>
                                <div className={styles.detailRow}>
                                    <span className={styles.label}>Generated:</span>
                                    <span className={styles.value}>
                                        {new Date(report.generated_at).toLocaleString()}
                                    </span>
                                </div>
                                {report.generated_by_name && (
                                    <div className={styles.detailRow}>
                                        <span className={styles.label}>Generated by:</span>
                                        <span className={styles.value}>{report.generated_by_name}</span>
                                    </div>
                                )}
                                {report.verified_by_name && (
                                    <div className={styles.detailRow}>
                                        <span className={styles.label}>Verified by:</span>
                                        <span className={styles.value}>{report.verified_by_name}</span>
                                    </div>
                                )}
                            </div>

                            <div className={styles.reportActions}>
                                {report.report_file && (
                                    <a
                                        href={report.report_file}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        className={styles.downloadButton}
                                    >
                                        📥 Download
                                    </a>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>
    );
}