# Generated by Django 5.2.7 on 2025-11-02 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mrn",
                    models.CharField(
                        help_text="Medical Record Number (auto-generated)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("father_name", models.CharField(max_length=255)),
                ("dob", models.DateField(help_text="Date of birth")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone must be a valid Pakistani mobile number",
                                regex="^(\\+92|0)?3\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "cnic",
                    models.CharField(
                        help_text="National ID in format #####-#######-#",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CNIC must be in format #####-#######-#",
                                regex="^\\d{5}-\\d{7}-\\d$",
                            )
                        ],
                    ),
                ),
                ("address", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "patients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["mrn"], name="patients_mrn_5d1fc1_idx"),
                    models.Index(fields=["cnic"], name="patients_cnic_7e2ed8_idx"),
                    models.Index(fields=["phone"], name="patients_phone_ef6690_idx"),
                ],
            },
        ),
    ]
