# Generated by Django 5.2.7 on 2025-11-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="is_offline_entry",
            field=models.BooleanField(
                default=False, help_text="True if originally created while offline"
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="origin_terminal",
            field=models.ForeignKey(
                blank=True,
                help_text="Terminal that created this registration (if known)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="core.labterminal",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when this record was synced to central server",
                null=True,
            ),
        ),
    ]
