# Generated by Django 5.2.7 on 2025-11-17 10:44

from django.db import migrations


def populate_default_permissions(apps, schema_editor):
    """Populate default role permissions."""
    RolePermission = apps.get_model("settings", "RolePermission")

    # Default permissions for each role
    default_permissions = [
        {
            "role": "ADMIN",
            "can_register": True,
            "can_collect": True,
            "can_enter_result": True,
            "can_verify": True,
            "can_publish": True,
            "can_edit_catalog": True,
            "can_edit_settings": True,
        },
        {
            "role": "RECEPTION",
            "can_register": True,
            "can_collect": False,
            "can_enter_result": False,
            "can_verify": False,
            "can_publish": False,
            "can_edit_catalog": False,
            "can_edit_settings": False,
        },
        {
            "role": "PHLEBOTOMY",
            "can_register": False,
            "can_collect": True,
            "can_enter_result": False,
            "can_verify": False,
            "can_publish": False,
            "can_edit_catalog": False,
            "can_edit_settings": False,
        },
        {
            "role": "TECHNOLOGIST",
            "can_register": False,
            "can_collect": False,
            "can_enter_result": True,
            "can_verify": False,
            "can_publish": False,
            "can_edit_catalog": False,
            "can_edit_settings": False,
        },
        {
            "role": "PATHOLOGIST",
            "can_register": False,
            "can_collect": False,
            "can_enter_result": False,
            "can_verify": True,
            "can_publish": True,
            "can_edit_catalog": False,
            "can_edit_settings": False,
        },
    ]

    for perm in default_permissions:
        RolePermission.objects.get_or_create(role=perm["role"], defaults=perm)


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_default_permissions),
    ]
