# Generated by Django 5.0 on 2025-12-05 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="pathologist_signature",
            field=models.FileField(
                blank=True, null=True, upload_to="signatures/pathologist/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="technician_signature",
            field=models.FileField(
                blank=True, null=True, upload_to="signatures/technician/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_generated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
