# Generated by Django 5.0 on 2025-12-27 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_priority_alter_order_status_and_more"),
        ("reports", "0002_report_pathologist_signature_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="amended_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Original report if this is an amendment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amendments",
                to="reports.report",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="amendment_reason",
            field=models.TextField(
                blank=True, help_text="Reason for creating this amendment", null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="delivered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_delivered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("print", "Printed"),
                    ("download", "Downloaded"),
                    ("sms", "SMS"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="last_reprinted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="report_number",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Unique report number (e.g., RPT-YYYYMMDD-NNNN)",
                max_length=50,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="reprint_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("FINAL", "Final"),
                    ("AMENDED", "Amended"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="template_name",
            field=models.CharField(
                default="default",
                help_text="Template used for report generation",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="is_final",
            field=models.BooleanField(
                default=True, help_text="Deprecated: Use status field instead"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["order", "status"], name="reports_rep_order_i_3dd99b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_number"], name="reports_rep_report__22888e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_at"], name="reports_rep_generat_35ba4e_idx"
            ),
        ),
    ]
