# Generated by Django 5.0 on 2026-02-11 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_report_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(help_text='Type of report (e.g., overview, finance)', max_length=50)),
                ('filters_json', models.JSONField(default=dict, help_text='Filters applied to the report')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('file_path', models.CharField(blank=True, help_text='Path to stored file if any', max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_key', 'generated_at'], name='reports_rep_report__5bf6d4_idx'), models.Index(fields=['user'], name='reports_rep_user_id_9dbc0a_idx')],
            },
        ),
    ]
