name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Lint with ruff
        run: |
          cd backend
          ruff check .
      - name: Format check with black
        run: |
          cd backend
          black --check .
      - name: Type check with mypy
        run: |
          cd backend
          mypy .
      - name: Run tests
        run: |
          cd backend
          pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          cd frontend
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - name: Lint
        run: |
          cd frontend
          npm run lint -- --max-warnings=0
      - name: Type check
        run: |
          cd frontend
          npm run type-check
      - name: Format check
        run: |
          cd frontend
          npm run format:check
      - name: Build
        run: |
          cd frontend
          npm run build
